# https://github.com/marketplace/actions/deploy-to-github-pages

name: docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install

      - name: Sphinx build
        run: |
          poetry run make html
          touch build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: build/html # The folder the action should deploy.
